### ISSUE TITLE
docker-compose v2

### ISSUE THREAD

**Issue by xmnlab** [conda-forge/docker-compose-feedstock#45]
### Additional comment:

hey everyone.

currently, the latest docker-compose conda-forge package is 1.29 https://github.com/conda-forge/docker-compose-feedstock/blob/main/recipe/meta.yaml#L2

docker-compose v2 was already released an now it is a go package instead of python.

I didn't play yet with docker-compose v2 .. but just checking here if anyone has any opinion about updating this package to v2.

from the documentation:

> From the end of June 2023 Compose V1 won’t be supported anymore and will be removed from all Docker Desktop versions.
> Make sure you switch to [Compose V2](https://docs.docker.com/compose/compose-file/) with the docker compose CLI plugin or by activating the Use Docker Compose V2 setting in Docker Desktop. For more information, see the [Evolution of Compose](https://docs.docker.com/compose/compose-v2/)

and something that caught my attention was: 

> V2 is not a standalone binary anymore, and installation scripts will have to be adjusted. 

not sure the impact about this yet.

any feedback would be very appreciated.

**Comment by hadim** [comment]
see https://github.com/conda-forge/docker-compose-feedstock/pull/46
